### ISSUE TITLE
One Experiment Missing : Week 6

### ISSUE THREAD

**Issue by rishi11** [BoruiGu/CS5610-borui#3]
There are only 4 experiments in week 6 (Node JS). Please perform atleast 5.

**Comment by BoruiGu** [comment]
I performed 6 experiments in week 6:
3 in Angular: Login, Login - redirect, Login - seperate files
3 in Node.js: Hello, Static, List management - select

I think we can perform experiments on any aspect and need not be limited to content of the current week. Please correct me if that is not true.
