### ISSUE TITLE
Week 7 : Experiments Missing

### ISSUE THREAD

**Issue by rishi11** [BoruiGu/CS5610-borui#4]
There should be at-least 5 experiments each week. Please complete the same.

**Comment by BoruiGu** [comment]
I performed 6 experiments in week 7:
2 in Angular: hover, hover-style
1 in Bootstrap: fixed-to-bottom
2 in CSS: border-radius, box-shadow
1 in Node.js: list-management-shift

please also refer to my reply in issue #3
